# Generated by Django 5.0.6 on 2024-07-19 07:17

import bill_report_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0003_alter_customuser_role_commanderprofile'),
        ('trip_management_app', '0002_alter_vehicle_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.CharField(default=bill_report_app.models.generate_bill_id, max_length=20)),
                ('amount', models.FloatField()),
                ('bill_date', models.DateTimeField(auto_now_add=True)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.driverprofile')),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip_management_app.trip')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip_management_app.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(default=bill_report_app.models.generate_contract_id, max_length=20)),
                ('amount', models.FloatField()),
                ('duration', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('description', models.TextField()),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.adminprofile')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.companyprofile')),
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.vendorprofile')),
            ],
        ),
    ]
