# Generated by Django 5.0.7 on 2024-07-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_report_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='trip_id',
        ),
        migrations.AddField(
            model_name='bill',
            name='company',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='report_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='vendor',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
