# Generated by Django 5.0.7 on 2024-07-27 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill_report_app', '0002_bill_total_amount_bill_tripdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='tripdate',
        ),
    ]
