# Generated by Django 5.0.7 on 2024-07-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_report_app', '0002_remove_bill_trip_id_bill_company_bill_report_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_date',
            field=models.DateTimeField(null=True),
        ),
    ]
