# Generated by Django 5.0.7 on 2024-07-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_report_app', '0003_remove_bill_total_amount_remove_bill_tripdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='kilometers',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_date',
            field=models.DateTimeField(null=True),
        ),
    ]
