# Generated by Django 5.0.7 on 2024-07-30 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_configuration'),
        ('bill_report_app', '0004_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.companyprofile'),
        ),
    ]
