# Generated by Django 5.0.7 on 2024-07-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_report_app', '0004_bill_kilometers_bill_rate_alter_bill_bill_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='role',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
