# Generated by Django 5.0.7 on 2024-07-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_report_app', '0005_bill_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='company',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
