# Generated by Django 5.0.7 on 2024-07-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_report_app', '0005_alter_bill_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='distance',
            field=models.FloatField(null=True),
        ),
    ]
