# Generated by Django 5.0.7 on 2024-07-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_report_app', '0006_bill_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='company',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='role',
        ),
        migrations.AddField(
            model_name='bill',
            name='report_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='daily', max_length=50),
        ),
    ]
