# Generated by Django 5.0.7 on 2024-07-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_report_app', '0006_bill_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='rate_per_km',
            field=models.FloatField(null=True),
        ),
    ]
