# Generated by Django 5.0.7 on 2024-07-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_report_app', '0007_remove_bill_company_remove_bill_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='access_level',
            field=models.CharField(choices=[('admin', 'Admin'), ('company', 'Company'), ('vendor', 'Vendor')], default='admin', max_length=50),
        ),
        migrations.AddField(
            model_name='bill',
            name='company_report_type',
            field=models.CharField(choices=[('summary', 'Summary'), ('detailed', 'Detailed')], default='summary', max_length=50),
        ),
    ]
