# Generated by Django 5.0.7 on 2024-07-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_report_app', '0008_bill_access_level_bill_company_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='report_type_value',
            field=models.FloatField(default=0.0),
        ),
    ]
