# Generated by Django 5.0.6 on 2024-08-09 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill_report_app', '0008_alter_bill_bill_date_alter_bill_company_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='driver_id',
            new_name='driver',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='trip_id',
            new_name='trip',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='vehicle_id',
            new_name='vehicle',
        ),
    ]
