# Generated by Django 5.0.6 on 2024-08-09 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill_report_app', '0009_rename_company_id_bill_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='admin_id',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='vendor_id',
            new_name='vendor',
        ),
    ]
