# Generated by Django 5.0.6 on 2024-08-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_report_app', '0010_rename_admin_id_contract_admin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Configuration',
        ),
        migrations.AlterField(
            model_name='bill',
            name='rate_per_km',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
