# Generated by Django 5.0.7 on 2024-07-24 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_management_app', '0002_alter_vehicle_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportrequest',
            name='vehicle',
        ),
    ]
