# Generated by Django 5.0.7 on 2024-07-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_management_app', '0003_rename_origin_latitude_route_source_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='end_meter_img',
            field=models.ImageField(blank=True, null=True, upload_to='meter_images/'),
        ),
        migrations.AddField(
            model_name='trip',
            name='pin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_meter_img',
            field=models.ImageField(blank=True, null=True, upload_to='meter_images/'),
        ),
    ]
