# Generated by Django 5.0.6 on 2024-08-01 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_adminprofile_aadhar_number_and_more'),
        ('trip_management_app', '0003_rename_origin_latitude_route_source_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='driver_id',
            new_name='driver',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='route_id',
            new_name='route',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='vehicle_id',
            new_name='vehicle',
        ),
        migrations.AddField(
            model_name='otherrequest',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.companyprofile'),
        ),
        migrations.AddField(
            model_name='route',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.companyprofile'),
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.companyprofile'),
        ),
        migrations.AddField(
            model_name='trip',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.companyprofile'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vendor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth_app.vendorprofile'),
            preserve_default=False,
        ),
    ]
