# Generated by Django 5.0.4 on 2024-07-30 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_customuser_role_commanderprofile'),
        ('trip_management_app', '0003_rename_origin_latitude_route_source_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='vendor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.vendorprofile'),
        ),
    ]
