# Generated by Django 5.0.6 on 2024-08-09 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_management_app', '0003_rename_origin_latitude_route_source_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otherrequest',
            old_name='driver_id',
            new_name='driver',
        ),
        migrations.RenameField(
            model_name='otherrequest',
            old_name='vehicle_id',
            new_name='vehicle',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='driver_id',
            new_name='driver',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='route_id',
            new_name='route',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='vehicle_id',
            new_name='vehicle',
        ),
    ]
