from django.db import models
from auth_app.models import DriverProfile, CompanyProfile, AdminProfile, VendorProfile
from trip_management_app.models import Trip, Vehicle
from auth_app.models import Configuration

from utils.useful_functions import generate_id

def generate_bill_id():
    return "BI" + generate_id()

def generate_contract_id():
    return "CT" + generate_id()

def generate_report_id():
    return "RP" + generate_id()

# Create your models here.
class Bill(models.Model):
    bill_id = models.CharField(max_length=20, default=generate_bill_id)
    trip = models.ForeignKey(Trip, on_delete=models.CASCADE)
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    company = models.ForeignKey(CompanyProfile, on_delete=models.CASCADE, null=True)
    driver = models.ForeignKey(DriverProfile, on_delete=models.CASCADE)
    amount = models.FloatField()
    bill_date = models.DateTimeField(auto_now_add=True, null=True)
    distance = models.FloatField(null=True)
    rate_per_km = models.FloatField(null=True, default=float(Configuration.objects.get_value('rate_per_km', default='0.0')))


    def __str__(self):
        return self.bill_id
    
class Contract(models.Model):
    contract_id = models.CharField(max_length=20, default=generate_contract_id)
    admin = models.ForeignKey(AdminProfile, on_delete=models.CASCADE)
    company = models.ForeignKey(CompanyProfile, on_delete=models.CASCADE)
    vendor = models.ForeignKey(VendorProfile, on_delete=models.CASCADE)
    amount = models.FloatField()
    duration = models.IntegerField()
    status = models.CharField(max_length=20, default="active", choices=(("active", "Active"), ("inactive", "Inactive")))
    description = models.TextField()
        
    def __str__(self):
        return self.contract_id
    
    
# Report will be a view generated by filtering and sorting the fields of Bill.

