# Generated by Django 5.0.6 on 2024-07-19 07:17

import auth_app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_adminprofile_aadhar_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('commander', 'Commander'), ('vendor', 'Vendor'), ('company', 'Company'), ('driver', 'Driver'), ('employee', 'Employee')], max_length=10),
        ),
        migrations.CreateModel(
            name='CommanderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commander_id', models.CharField(default=auth_app.models.generate_commander_id, max_length=20)),
                ('contact_number', models.IntegerField()),
                ('address', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('aadhar_number', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
