# Generated by Django 5.0.6 on 2024-07-19 07:19

import django.db.models.deletion
import notification_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0003_alter_customuser_role_commanderprofile'),
        ('trip_management_app', '0002_alter_vehicle_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_id', models.CharField(default=notification_app.models.generate_alert_id, max_length=20)),
                ('alert_type', models.CharField(choices=[('live', 'Live'), ('sos', 'SOS'), ('network', 'Network'), ('location', 'Location'), ('speed', 'Speed'), ('delay', 'Delay'), ('idle', 'Idle')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('alert_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=20)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.driverprofile')),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip_management_app.trip')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip_management_app.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='SafetyLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safety_log_id', models.CharField(default=notification_app.models.generate_safety_log_id, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('alert_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification_app.alerts')),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.driverprofile')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.employeeprofile')),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip_management_app.trip')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip_management_app.vehicle')),
            ],
        ),
    ]
